"""Send a deterministic Plenipo local-lab ping and wait for an ack."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import secrets
from pathlib import Path
from time import monotonic
from typing import Any

from plenipo.mcp.runtime import McpRuntime, load_mcp_config_from_env


async def main() -> int:
    parser = argparse.ArgumentParser(description='Send deterministic Plenipo local-lab ping.')
    parser.add_argument('--env', help='Private env file generated by scripts/create_local_identity.py')
    parser.add_argument('--recipient-did', required=True)
    parser.add_argument('--recipient-document-url')
    parser.add_argument('--timeout-ms', type=int, default=120_000)
    args = parser.parse_args()

    if args.env:
        _load_env_file(Path(args.env))

    runtime = McpRuntime(load_mcp_config_from_env())
    await runtime.ensure_connected()
    print(f'Sender connected as {os.environ["PLENIPO_DID"]}')
    print(f'Sender balance: {await runtime.get_balance()}')

    nonce = secrets.token_urlsafe(16)
    ping = {
        'kind': 'plenipo.local.ping',
        'nonce': nonce,
        'sender': os.environ['PLENIPO_DID'],
    }

    ack = await runtime.send(
        args.recipient_did,
        json.dumps(ping, separators=(',', ':')),
        args.recipient_document_url,
    )
    print(f'Ping sent with envelope {ack["envelope_id"]} ({ack["status"]}).')

    deadline = monotonic() + args.timeout_ms / 1000
    while monotonic() < deadline:
        for entry in runtime.drain_messages(limit=100):
            if entry.kind != 'deliver' or not entry.plaintext:
                continue

            payload = _parse_json(entry.plaintext)
            if payload.get('kind') == 'plenipo.local.ack' and payload.get('nonce') == nonce:
                print(f'Ack received from {entry.sender_did} in envelope {entry.envelope_id}.')
                return 0

        await asyncio.sleep(0.5)

    raise TimeoutError(f'Timed out waiting for ack from {args.recipient_did}')


def _load_env_file(path: Path) -> None:
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#'):
            continue

        key, separator, value = line.partition('=')
        if separator:
            os.environ[key] = value


def _parse_json(value: str) -> dict[str, Any]:
    try:
        payload = json.loads(value)
    except json.JSONDecodeError:
        return {}

    return payload if isinstance(payload, dict) else {}


if __name__ == '__main__':
    raise SystemExit(asyncio.run(main()))
